server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ewm
    username: praktikum
    password: praktikum
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  sql:
    init:
      platform: postgresql
      mode: always

stats:
  service:
    url: http://localhost:9090

logging:
  level:
    ru.practicum.ewmservice: DEBUG
    org.hibernate.SQL: WARN
    org.springframework.web: INFO